### ISSUE TITLE
FIRST_HOLE metadata value can refer to spurious hole, leading to bad MIDI tick values

### ISSUE THREAD

**Issue by broadwell** [sul-cidr/roll-image-parser#2]
The documentation suggests that the `FIRST_HOLE` metadata value should correspond to the Y pixel coordinate of the first hole and also to tick 0 of the first MIDI event, from which the tick values of all further MIDI playback events (corresponding to subsequent holes) will be assigned as offsets. When the Y coordinate of a hole that is not assigned any control or note meaning by `tiff2holes` is nonetheless designated as `FIRST_HOLE`, the MIDI tick values can no longer be used in conjunction with this value to determine which row on the roll image corresponds to a specific MIDI event; this error also can cause an excessive amount of silence to be encoded into the beginning of the MIDI file, because the first actual control or note event may happen many ticks/pixels later on the roll.

**Example problematic roll: yj598pj2879** (Welte red)
The roll image processing logic in `src/RollImage.cpp` records the roll's `FIRST_HOLE` value as belonging to a marginal hole, partially covered by tape (see image below -- probably it's related to the rewind system?) that is not included in the arrays of consequential control and music holes, yet the MIDI tick values for each subsequent hole are still calculated as offsets from this position, rather than the position of the first "real" control/music hole. This leads the MIDI tick values and hole Y coordinates on the roll to be off by 190, i.e., the MIDI tick values are 190 ticks too "late", so when highlighting the MIDI "play" position on the roll image, the play line always appears 190 pixels too far ahead on the roll.
There is no key,value stored in the MIDI metadata track (track 0) that would enable a player app to resolve this discrepancy, though it likely could be detected if the extended hole location report from `tiff2holes` is available.
![Screen Shot 2021-03-23 at 4 54 52 PM](https://user-images.githubusercontent.com/7329112/112233893-871e6b00-8bf8-11eb-9878-4f49f46ca79e.png)

The [fix_midi_alignment](https://github.com/sul-cidr/roll-image-parser/tree/fix_midi_alignment) branch proposes a fix -- using the position of the first consequential control or note hole for `FIRST_HOLE` -- but the modified code has not been run on multiple rolls, and so far there is only the one confirmed error case (see above) to test against.

**Comment by simonwiles** [comment]
I think this is closed by #8?
